description: "A new Flutter project."
name: pixel_adventure
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flame: ^1.22.0
  flame_bloc: ^1.12.4
  flame_tiled: ^1.21.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  logger: ^2.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/characters/mask_dude/
    - assets/images/items/checkpoint/
    - assets/images/items/fruits/
    - assets/images/characters/
    - assets/images/background/
    - assets/images/items/saw/
    - assets/images/terrain/
    - assets/images/hud/
    - assets/audio/
    - assets/tiles/
